# Copyright (c) 2020 Intel Corporation.

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

apiVersion: v1
kind: Service
metadata:
  name: etcd-ui
  namespace: kube-eis
spec:
  type: NodePort
  selector:
    app: etcd-ui
  ports:
  - port: 7070
    targetPort: 7070
    nodePort: 30010
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd-ui
  name: ia-etcd-ui
  namespace: kube-eis
spec:
  containers:
  - name: ia-etcd-ui
    image: ia_etcd_ui:${EIS_VERSION}
    volumeMounts:
    - name: etcd-keeper
      mountPath: /tmp/nginx
    - name: "ca-cert"
      mountPath: /run/secrets/ca_etcd
    - name: "etcd-ui-cert"
      mountPath: /run/secrets/etcd_EtcdUI_cert
    - name: "etcd-ui-key"
      mountPath: /run/secrets/etcd_EtcdUI_key
    - name: "etcd-user-cert"
      mountPath: /run/secrets/etcd_etcduser_cert
    - name: "etcd-user-key"
      mountPath: /run/secrets/etcd_etcduser_key
    env:
    - name: AppName
      value: "EtcdUI"
    - name: DEV_MODE
      value: '${DEV_MODE}'
    - name: NGINX_PORT
      value: "7071"
    - name: no_proxy
      value: '${eis_no_proxy}'
    - name: ETCD_HOST
      value: etcd
    - name: ETCD_CLIENT_PORT
      value: '${ETCD_CLIENT_PORT}'
    - name: PROVISION_MODE
      value: '${PROVISION_MODE}'
    - name: ETCD_PREFIX
      value: '${ETCD_PREFIX}'
    - name: ETCD_ENDPOINT
      value: 'etcd:$ETCD_CLIENT_PORT'
    - name: ETCD_USER
      value: "root"
    - name: CONFIGMGR_CACERT
      value: "/run/secrets/ca_etcd/ca_certificate.pem"
    - name: CONFIGMGR_CERT
      value: "/run/secrets/etcd_EtcdUI_cert/EtcdUI_client_certificate.pem"
    - name: CONFIGMGR_KEY
      value: "/run/secrets/etcd_EtcdUI_key/EtcdUI_client_key.pem"
  volumes:
  - name: etcd-keeper
    hostPath:
      path: /tmp/nginx
  - name: "ca-cert"
    secret:
      secretName: ca-etcd
  - name: "etcd-ui-cert"
    secret:
      secretName: etcdui-cert
  - name: "etcd-ui-key"
    secret:
      secretName: etcdui-key
  - name: "etcd-user-cert"
    secret:
      secretName: root-cert
  - name: "etcd-user-key"
    secret:
      secretName: root-key
